/* FooterComponent.js
   Pure JS DOM footer builder – generated by Cascade
   Usage:
     1. Include this script (module or regular) after the DOM or with defer.
     2. Call window.FooterComponent.load(parent?) – parent defaults to document.body.
*/

(function (global) {
  'use strict';

  /* --------------------------------------------------
   * Phase 1 – Bootstrapping (data + helpers + FA link)
   * -------------------------------------------------- */

  /* Data model */
  const DATA = {
    logo: {
      src: 'assets/chef-preview.png',
      alt: 'Logo'
    },
    marketingHTML: 'Open an account in minutes,<br />get full financial control for much longer.',

    columns: [
      {
        heading: 'Company',
        links: [
          { href: 'about.html', icon: 'fa-building', text: 'About' },
          { href: 'policcies.html', icon: 'fa-file-contract', text: 'Terms and Conditions' },
          { href: '#', icon: 'fa-blog', text: 'Blog' },
          { href: 'menu.html', icon: 'fa-utensils', text: 'Menu' },
          { href: '#', icon: 'fa-cogs', text: 'How we work?' }
        ]
      },
      {
        heading: 'Links',
        links: [
          { href: 'cheifs.html', icon: 'fa-user-tie', text: 'Chefs' },
          { href: 'services.html', icon: 'fa-concierge-bell', text: 'Services' },
          { href: 'review.html', icon: 'fa-star', text: 'Review' },
          { href: 'policcies.html', icon: 'fa-shield-alt', text: 'Policies' },
          { href: '#', icon: 'fa-store-alt', text: 'Restaurant Management' }
        ]
      },
      {
        heading: 'More',
        links: [
          { href: 'home.html', icon: 'fa-home', text: 'Home' },
          { href: '#', icon: 'fa-users', text: 'Customer Engagement' },
          { href: 'recipe.html', icon: 'fa-book-open', text: 'Recipes' }
        ]
      }
    ],

    social: [
      { href: '#', src: 'assets/facebook.png', alt: 'Facebook' },
      { href: '#', src: 'assets/instagram.png', alt: 'Instagram' },
      { href: '#', src: 'assets/twitter.png', alt: 'Twitter' }
    ],

    copyright: '© 2025 Made with ❤️ by Farida Mohamed'
  };

  /* Helpers */
  const el = (tag, className) => {
    const element = document.createElement(tag);
    if (className) element.classList.add(className);
    return element;
  };

  const setAttrs = (element, attrs) => {
    Object.entries(attrs || {}).forEach(([k, v]) => {
      element.setAttribute(k, v);
    });
    return element;
  };

  const ensureFontAwesome = () => {
    if (!document.querySelector('link[href*="font-awesome"]')) {
      const link = setAttrs(document.createElement('link'), {
        rel: 'stylesheet',
        href: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css',
        integrity: 'sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==',
        crossorigin: 'anonymous',
        referrerpolicy: 'no-referrer'
      });
      document.head.appendChild(link);
    }
  };

  /* --------------------------------------------------
   * Phase 2 – Sub-component builders
   * -------------------------------------------------- */

  const buildLogoSection = () => {
    const container = el('div', 'footer-logo');

    const img = setAttrs(el('img'), { src: DATA.logo.src, alt: DATA.logo.alt });
    const p = el('p', 'footer-text');
    p.innerHTML = DATA.marketingHTML;

    container.appendChild(img);
    container.appendChild(p);
    return container;
  };

  const buildLinksSection = (columnsData) => {
    const wrapper = el('div', 'footer-links');

    columnsData.forEach(col => {
      const column = el('div', 'footer-column');
      const heading = document.createElement('h4');
      heading.textContent = col.heading;
      column.appendChild(heading);

      col.links.forEach(linkData => {
        const a = setAttrs(el('a'), { href: linkData.href });
        a.innerHTML = `<i class="fas ${linkData.icon}"></i> ${linkData.text}`;
        column.appendChild(a);
      });

      wrapper.appendChild(column);
    });
    return wrapper;
  };

  const buildSocialIcons = (socialData) => {
    const wrapper = el('div', 'social-icons2');
    socialData.forEach(icon => {
      const a = setAttrs(el('a'), { href: icon.href });
      const img = setAttrs(el('img'), { src: icon.src, alt: icon.alt });
      a.appendChild(img);
      wrapper.appendChild(a);
    });
    return wrapper;
  };

  const buildBottomBar = () => {
    const footer = el('footer', 'footer2');
    const p = document.createElement('p');
    p.textContent = DATA.copyright;
    footer.appendChild(p);
    return footer;
  };

  /* --------------------------------------------------
   * Phase 3 – Assembly & Exposure
   * -------------------------------------------------- */

  const createFooter = (parent = document.body) => {
    ensureFontAwesome();

    // Wrapper .footer
    const footerWrapper = el('div', 'footer');

    // .footer-content holds logo + links
    const footerContent = el('div', 'footer-content');
    footerContent.appendChild(buildLogoSection());
    footerContent.appendChild(buildLinksSection(DATA.columns));
    footerWrapper.appendChild(footerContent);

    // social icons row
    footerWrapper.appendChild(buildSocialIcons(DATA.social));

    // Append wrapper and bottom bar to parent
    parent.appendChild(footerWrapper);
    parent.appendChild(buildBottomBar());

    return footerWrapper;
  };

  /* Expose API */
  const api = { load: createFooter };

  if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
    module.exports = api;
  } else {
    global.FooterComponent = api;
  }
})(typeof window !== 'undefined' ? window : this);
